### ISSUE TITLE
canot start this engine...

### ISSUE THREAD

**Issue by dingjibang** [nondev/nonlua#3]
hey,
this project looks like awesome,and I have try to import it by gradle.
but some issues when I run this project:
    Exception in thread "main" java.lang.UnsatisfiedLinkError: io.nondev.nonlua.Lua.jniOpen(I)Lio/nondev/nonlua/CPtr;
    at io.nondev.nonlua.Lua.jniOpen(Native Method)
    at io.nondev.nonlua.Lua.<init>(Lua.java:506)
    at com.rpsg.rpg.view.GameViews.<init>(GameViews.java:55)
    at com.rpsg.rpg.desktop.DesktopLauncher.main(DesktopLauncher.java:40)

my op-system is win10-64 and win7-64

**Comment by deathbeam** [comment]
This project is on hold until I will buy Mac (which will be on 14th-20th august) so I will be able to add support for all platforms and architectures. But for now, this supports only 32bit architectures because I have 32 bit PC and I was able to compile natives only for 32bit platforms.

**Comment by dingjibang** [comment]
ooohhh!come on,i'm watching it
